/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameId = IDL.Text;
export const Game = IDL.Record({
  'id' : GameId,
  'title' : IDL.Text,
  'thumbnail' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'playCount' : IDL.Nat,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'isNew' : IDL.Bool,
  'embedUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFeaturedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getGameById' : IDL.Func([IDL.Text], [IDL.Opt(Game)], ['query']),
  'getGamesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
  'getNewGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'searchGames' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameId = IDL.Text;
  const Game = IDL.Record({
    'id' : GameId,
    'title' : IDL.Text,
    'thumbnail' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'playCount' : IDL.Nat,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'isNew' : IDL.Bool,
    'embedUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFeaturedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getGameById' : IDL.Func([IDL.Text], [IDL.Opt(Game)], ['query']),
    'getGamesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
    'getNewGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'searchGames' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };